services:
  - type: web
    name: descarga-todo-app
    env: python
    plan: free
    buildCommand: "./render-build.sh"
    startCommand: "gunicorn --worker-class gevent --bind 0.0.0.0:$PORT app:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
<<<<<<< HEAD
      - key: REDIS_URL
        fromService:
=======
        key: REDIS_URL
      - fromService:
>>>>>>> 2bbb09a6255b68a92e02780182a213ac74e232e0
          type: redis
          name: cache
          property: connectionString

  - type: redis
    name: cache
    plan: free
     ipAllowList:
      - source: 0.0.0.0/0
        description: "Permitir todas las conexiones"
