services:
  - type: web
    name: descarga-todo-app
    env: python
    plan: free
    buildCommand: "./render-build.sh"
    startCommand: "export PATH=\"${PATH}:/opt/render/project/.render/chrome/opt/google/chrome\"; gunicorn --workers 2 --worker-class gevent --bind 0.0.0.0:$PORT app:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: REDIS_URL
        fromService:
          type: redis
          name: cache
          property: connectionString

  - type: redis
    name: cache
    plan: free
    ipAllowList:
      - source: 0.0.0.0/0
        description: "Permitir todas las conexiones"